language: cpp

jobs:
  include:
#==============================================================================================================================================================
    - stage: Build tulip-python wheels and upload to test.pypi.org
      os: osx
      osx_image: xcode9.4
      cache: ccache
      install:
        - |
          cat > ~/.pypirc << EOF
          [distutils]
          index-servers=
              testpypi

          [testpypi]
          repository: https://test.pypi.org/legacy/
          username: anlambert
          password: $TESTPYPI_PWD

        - export COLUMNS=80
        - wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        - chmod +x ./macports-ci
        - travis_wait ./macports-ci install
        - export PATH=/opt/local/bin:$PATH
        - sudo port -N install cmake
        - sudo port -N install clang-7.0
        - sudo port -N install ccache
        - sudo port -N install ninja
        - sudo port -N install qhull
        - sudo port -N install yajl
        - curl -LO https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.9.pkg
        - sudo installer -pkg python-2.7.15-macosx10.9.pkg -target /
        - sudo /Library/Frameworks/Python.framework/Versions/2.7/bin/pip install wheel
        - sudo /Library/Frameworks/Python.framework/Versions/2.7/bin/pip install twine
        - curl -LO https://www.python.org/ftp/python/3.7.0/python-3.7.0-macosx10.9.pkg
        - sudo installer -pkg python-3.7.0-macosx10.9.pkg -target /
        - sudo /Library/Frameworks/Python.framework/Versions/3.7/bin/pip3 install wheel
        - sudo /Library/Frameworks/Python.framework/Versions/3.7/bin/pip3 install twine
      script:
        - LAST_VERSION=$(curl -s 'https://test.pypi.org/pypi/tulipe-python/json' | python -c "import sys, json; print(json.load(sys.stdin)['info']['version'])" 2>/dev/null)
        - DEV_VERSION=$(echo $LAST_VERSION | cut -f4 -d '.' | sed 's/dev//')
        - let DEV_VERSION+=1
        - mkdir build && cd build
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-7.0 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-7.0 -DTULIP_ACTIVATE_PYTHON_WHEEL_TARGET=ON -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/2.7/bin/python -DTULIP_USE_CCACHE=ON -DTULIP_PYTHON_TEST_WHEEL_SUFFIX=dev${DEV_VERSION} || travis_terminate 1
        - ninja -j4 test-wheel || travis_terminate 1
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-7.0 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-7.0 -DTULIP_ACTIVATE_PYTHON_WHEEL_TARGET=ON -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -DTULIP_USE_CCACHE=ON -DTULIP_PYTHON_TEST_WHEEL_SUFFIX=dev${DEV_VERSION} || travis_terminate 1
        - ninja -j4 test-wheel || travis_terminate 1
        - ninja test-wheel-upload
      env:
        secure: "gC/3avSch56PVS5w/n2E33nXj0H9YpmXk9FK6GWyVoFKF0M4inaJQu6jhj76TpvT3dXwSZCXHC4ubckamN771AakF7wqcClPqF6uWc1q6Vog9/SEut5pbQq762aVgdHkHw6W9xxMUJf/tENQLyk1MT46ZuTmBjKI5Y3Z0CN4eUqYb6gFED7ReP7Z25R0lK/AkFjEhdLotAA9ghHPbloRQB/EZSNYohEUf7fjKs1nSa+BDuyKwMJWLWgTuO6CI7U+FS1x1DCepRrOh+sOYyiexmReuxblcdpAOQYRUIMIL36XK1FWXvhmFbk6iPaSJm/JPNhrmCz7mgXEwIH/WGQ3e+WkOjux+cJKMl7RF0GgzGB8j6F94kLodIk3QZ0IajvaXKRUZWykMWeRUel//5KJZMIcoqbpBt6S4L7dKhvkBZnUQxuAHlW7dcwsjrrY1LlygaFIFXMugqys1ozHJ765SOMNHqrTF7hshc7WZIOQ1I/+Xs2Hg0cUSJjfhWV2AvRipqORRe600hMDjSue4oPmEp0RvVj19vjDc2815HOQ8u7qg2wANakRhE6rR2FTPT7dFNFjvAn7UOuH5TvCYoYPvFCnSvU+bhQKfCSfRmv+nbx7nAqHvQw+EWzY6p8ccbyEDO+G7oNqi1bjzy7S+BAJFPuOQJxyyWIu1w6YItrZLlU="

    - stage: Test tulip-python installation on clean systems
      os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_PROVIDER=Apple
      script:
        - python --version
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - sudo python get-pip.py
        - sudo pip install --index-url https://test.pypi.org/simple/ tulipe-python
        - python -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"

    -
      os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_PROVIDER=Python.org
      install:
        - curl -LO https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.9.pkg
        - sudo installer -pkg python-2.7.15-macosx10.9.pkg -target /
        - curl -LO https://www.python.org/ftp/python/3.7.0/python-3.7.0-macosx10.9.pkg
        - sudo installer -pkg python-3.7.0-macosx10.9.pkg -target /
      script:
        - python2.7 --version
        - sudo pip2.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python2.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
        - sudo pip3.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python3.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"

    -
      os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_PROVIDER=MacPorts
      install:
        - export COLUMNS=80
        - wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        - chmod +x ./macports-ci
        - travis_wait ./macports-ci install
        - export PATH=/opt/local/bin:$PATH
        - sudo port -N install python27
        - sudo port -N install py27-pip
        - sudo port -N install python37
        - sudo port -N install py37-pip
      script:
        - python2.7 --version
        - sudo pip-2.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python2.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
        - sudo pip-3.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python3.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"

    -
      os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_PROVIDER=Homebrew
      addons:
        homebrew:
          packages:
            - python2
            - python3
          update: true
      script:
        - python2.7 --version
        - sudo pip2.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python2.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
        - sudo pip3.7 install --index-url https://test.pypi.org/simple/ tulipe-python
        - python3.7 -c "from tulip import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
