language: cpp

cache:
  directories:
  - $HOME/ccache

sudo: required
env:
  matrix:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull ${DOCKER_IMAGE}

script:
  - sudo docker run --rm=true -e CCACHE_DIR=/ccache -v $PWD:/tulip:rw -v $HOME/ccache:/ccache:rw ${DOCKER_IMAGE} /bin/bash -c "bash -xe /tulip/bundlers/python/tulip_manylinux_wheels_build.sh"
