# Talipot continuous integration on windows platform through AppVeyor.
# Talipot will be compiled for 32 bits and 64 bits windows using :
#   - GCC compiler provided by the MSYS2 project
#   - Microsoft Visual Studio 2015 compiler
# C++11 standard, Qt >= 5.9 and Python 3.7 will be used to build Talipot with both compilers.

# use Visual Studio 2017 appveyor image for the builds
os: Visual Studio 2017

# Use build caches that will be saved and restored between build jobs.
# Those caches will hold ccache content for gcc builds and clcache content for msvc builds
# in order to speedup incremental builds.
# Appveyor cache storage is limited to 1GB, so cache should be cleared once it is exceeding this quota
# (see https://www.appveyor.com/docs/build-cache/)
cache:
  - C:\msys64\home\appveyor\.ccache
  - C:\Users\appveyor\clcache
  - C:\Tools\vcpkg\installed\

init:
  - ps: $env:APPVEYOR_SAVE_CACHE_ON_ERROR = "true"

# define build jobs
environment:
  matrix:
    # GCC core build
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON_HOME: "C:/Python38-x64"
      BUILD_WHEELS: false

    # GCC complete build
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON_HOME: "C:/Python38-x64"
      BUILD_WHEELS: false

    # GCC Python wheels build
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      BUILD_WHEELS: true
      TWINE_REPOSITORY: https://test.pypi.org/legacy/
      TWINE_USERNAME: __token__
      TWINE_PASSWORD:
        secure: 69gKUYg72j5gedVBM/dWr+0D2rTf/IxMcQ0mBVxat0e9P4Mkv
                ubhOsDIHKSOtnUc9WN3ns1Z8KLbESG/wvmVs4kaWQzLDcopID
                1obaaNl2bt9E2GliNcbAgEiHEHp7dj+nVkGw0ur32Yi4F2OJN
                dg57bgn2mRZWfK+3qBUPIhzaH5PqJ7FW4qKADpiANyHs+8EES
                sxXIe/QPXpqPeAjbwdrcJ7QmL2vIllXthlGgryWyg62ZE6kIy
                Dy+jye9nWLq

    # MSVC core build
    - CMAKE_VS_GENERATOR: "Visual Studio 15 2017 Win64"
      MSVC_PLATFORM: "x64"
      MSVC_PLATFORM_TOOLSET: "v141"
      QT5_DIR: "C:/Qt/5.13/msvc2017_64"
      PYTHON_EXECUTABLE: "C:/Python38-x64/python.exe"

    # MSVC complete build
    - CMAKE_VS_GENERATOR: "Visual Studio 15 2017 Win64"
      MSVC_PLATFORM: "x64"
      MSVC_PLATFORM_TOOLSET: "v141"
      QT5_DIR: "C:/Qt/5.13/msvc2017_64"
      PYTHON_EXECUTABLE: "C:/Python38-x64/python.exe"

# build script that simply call the right batch script depending on the compiler used
build_script:
  - if defined MSYS2_ARCH (
      "%APPVEYOR_BUILD_FOLDER%\appveyor_msys2.bat" %BUILD_WHEELS%
    ) else (
      "%APPVEYOR_BUILD_FOLDER%\appveyor_msvc.bat"
    )

# get the Talipot version for deployment
after_build:
  - ps: "$env:TALIPOT_VERSION = (((Get-Content ($env:APPVEYOR_BUILD_FOLDER +
         '/build/library/talipot-core/include/talipot/Release.h') |
         %{ if ($_ -match '^#   define TALIPOT_VERSION.*$') { $_; } })
         -replace '#   define TALIPOT_VERSION ', '') -replace '\"', ''
         -replace '_', '.')"

# set generated installers as artifacts to deploy
artifacts:
  - path: build\*.exe
    name: talipot_installers

# deploy Talipot installers on bintray
deploy:
  - provider: BinTray
    on:
      branch: master
    username: anlambert
    api_key:
      secure: uL6yGLvWIQkeqyYKFzshycul9WpaBj5P4SYUvtAnlcpxaDhL3Ek+sxm+XRYFfH7n
    subject: anlambert
    repo: talipot_binaries
    package: Talipot
    version: $(TALIPOT_VERSION)
    publish: true
    override: true
    artifact: talipot_installers

