[build-system]
requires = ["sip >=6, <7"]
build-backend = "sipbuild.api"

[project]
name = "talipot"

[tool.sip.project]
sip-include-dirs = ["../stl"]
sip-module = "talipot.native.sip"

[tool.sip.bindings.talipot]
concatenate = 12
