name: appimage-build
on: [push, pull_request]
jobs:
  appimage:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Talipot AppImage build on CentOS 7
            docker-image: centos:7
          - name: Talipot AppImage build on CentOS 8
            docker-image: centos:8
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v2
      - name: Get current date
        id: get-current-date
        run: |
          echo "::set-output name=date::$(date -u "+%Y-%m-%d-%H-%m-%S")"
        shell: bash
      - name: Cache files
        uses: actions/cache@v2
        with:
          path: ~/ccache
          key: appimage-${{ matrix.config.docker-image }}-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            appimage-ccache-
      - name: Pull ${{ matrix.config.docker-image }} docker image
        run: sudo docker pull ${{ matrix.config.docker-image }}
      - name: Create ccache docker volume
        run: sudo docker create
          -v ~/ccache:/ccache
          --name ccache
          ${{ matrix.config.docker-image }}
      - name: Build Talipot AppImage in CentOS
        run: sudo docker run
          -e CCACHE_DIR=/ccache
          --volumes-from ccache
          -v `pwd`:/talipot:rw
          ${{ matrix.config.docker-image }}
          /bin/bash -c "bash -xe /talipot/bundlers/linux/talipot_appimage_centos_build.sh"
      - name: Get Talipot version
        id: get-talipot-version
        run: |
          echo "::set-output name=version::$(bash build/talipot-config --version)"
        shell: bash
      - name: Upload Taliot AppImage to GitHub Actions artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Talipot AppImages
          path: ./build/Talipot*.AppImage
