name: archlinux-build
on: [push, pull_request]
jobs:
  archlinux:
    name: Talipot build on ArchLinux
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
      - name: Checkout Talipot code
        uses: actions/checkout@v2
      - name: Get current date
        id: get-current-date
        run: |
          echo "::set-output name=date::$(date -u "+%Y-%m-%d-%H-%m-%S")"
        shell: bash
      - name: Cache files
        uses: actions/cache@v2
        with:
          path: ~/ccache
          key: archlinux-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            archlinux-ccache-
      - name: Pull archlinux docker image
        run: sudo docker pull archlinux
      - name: Create ccache docker volume
        run: sudo docker create
          -v ~/ccache:/ccache
          --name ccache
          archlinux
      - name: Build Talipot on ArchLinux
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          shell: bash
          options: -e CCACHE_DIR=/ccache
            --volumes-from ccache
            -v ${{ github.workspace }}:/talipot:rw
          run: |
            pacman --noconfirm -Syuu

            pacman --noconfirm -S \
              cmake \
              ccache \
              base-devel \
              git \
              gcc \
              qhull \
              yajl \
              graphviz \
              python \
              cppunit \
              binutils \
              zstd \
              libgit2 \
              qt6-base \
              qt6-webengine \
              quazip-qt6 \
              glew \
              freetype2 \
              fribidi \
              fontconfig \
              python-sphinx \
              xorg-server-xvfb

            mkdir /talipot_build
            cd /talipot_build

            cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=$PWD/install \
              -DTALIPOT_USE_CCACHE=ON \
              -DTALIPOT_USE_QT6=ON \
              -DTALIPOT_BUILD_TESTS=ON \
              ../talipot

            make -j4 install
            xvfb-run  make -j4 tests
