name: archlinux-build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  archlinux:
    name: Talipot build on ArchLinux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v4
      - name: Get current date
        id: get-current-date
        run: |
          echo "date=$(date -u "+%Y-%m-%d-%H-%m-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: ~/ccache
          key: archlinux-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            archlinux-ccache-
          save-always: true
      - name: Pull archlinux docker image
        run: docker pull archlinux
      - name: Create ccache docker volume
        run: docker create
          -v ~/ccache:/ccache
          --name ccache
          archlinux
      - name: Build Talipot on ArchLinux
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          shell: bash
          options: -e CCACHE_DIR=/ccache
            --volumes-from ccache
            -v ${{ github.workspace }}:/talipot:rw
          run: |
            pacman --noconfirm -Syuu

            pacman --noconfirm -S \
              cmake \
              ccache \
              base-devel \
              git \
              gcc \
              qhull \
              yajl \
              graphviz \
              python \
              cppunit \
              binutils \
              zstd \
              libgit2 \
              qt6-base \
              quazip-qt6 \
              glew \
              glu \
              freetype2 \
              fribidi \
              fontconfig \
              python-sphinx \
              sip \
              xorg-server-xvfb

            mkdir /talipot_build
            cd /talipot_build

            cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=$PWD/install \
              -DTALIPOT_USE_CCACHE=ON \
              -DTALIPOT_USE_QT6=ON \
              -DTALIPOT_BUILD_TESTS=ON \
              ../talipot

            make -j4 install
            xvfb-run  make -j4 tests
            xvfb-run  ./install/bin/talipot \
              --check-application-starts \
              --debug-plugins-load
