name: code-coverage
on: [push, pull_request]
jobs:
  ubuntu:
    name: Talipot C++ code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout Talipot code
        uses: actions/checkout@v4
      - name: Apt update
        run: sudo apt update
      - name: Install Talipot build dependencies
        run: sudo apt install
          cmake
          ccache
          ninja-build
          libqhull-dev
          libyajl-dev
          libgraphviz-dev
          libpython3-dev
          libcppunit-dev
          binutils-dev
          libzstd-dev
          libgit2-dev
          qtbase5-dev
          libqt5webkit5-dev
          libquazip5-dev
          libglew-dev
          libfreetype6-dev
          libfribidi-dev
          libfontconfig-dev
          python3
          python3-pip
          doxygen
          graphviz
          xvfb
      - name: Install sip
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install sip
      - name: Prepare ccache timestamp
        id: get-current-date
        run: |
          echo "date=$(date -u "+%Y-%m-%d-%H-%m-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ matrix.config.os }}-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            ${{ matrix.config.os }}-ccache-
          save-always: true
      - name: Create build directory
        run: mkdir build
      - name: Configure Talipot build with CMake
        working-directory: ./build
        run: cmake .. -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=$PWD/install
          -DTALIPOT_BUILD_TESTS=ON
          -DTALIPOT_USE_CCACHE=ON
          -DTALIPOT_BUILD_DOC=OFF
          -DTALIPOT_CODE_COVERAGE=ON
      - name: Talipot build
        working-directory: ./build
        run: ninja -j4
      - name: Run Talipot unit tests
        working-directory: ./build
        run: xvfb-run ninja tests
      - name: Generate and upload code coverage report
        uses: threeal/gcovr-action@main
        with:
          excludes: |
            build/*
            library/talipot-gui/*
            library/talipot-ogl/*
            library/talipot-python/*
            plugins/interactor/*
            plugins/view/*
            software/*
            tests/*
            thirdparty/*
            utils/*
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
