name: macos-homebrew-build
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Talipot build on MacOS 10.15
            os: macos-10.15
          - name: Talipot build on MacOS 11.0
            os: macos-11.0
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v2
      - name: Install Talipot build dependencies
        run: brew install
          ccache
          cmake
          llvm
          qhull
          yajl
          zstd
          python3
          cppunit
          pkg-config
          glew
          freetype
          fontconfig
          qt5
          quazip
      - name: Prepare ccache timestamp
        id: get-current-date
        run: |
          echo "::set-output name=date::$(date -u "+%Y-%m-%d-%H-%m-%S")"
        shell: bash
      - name: Cache files
        uses: actions/cache@v2
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ${{ matrix.config.os }}-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            ${{ matrix.config.os }}-ccache-
      - name: Create build directory
        run: mkdir build
      - name: Configure Talipot core build with CMake
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=$PWD/install
          -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang
          -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
          -DPYTHON_EXECUTABLE=/usr/local/bin/python3
          -DTALIPOT_BUILD_CORE_ONLY=ON
          -DTALIPOT_BUILD_TESTS=ON
          -DTALIPOT_BUILD_DOC=OFF
          -DTALIPOT_USE_CCACHE=ON
      - name: Talipot core build
        working-directory: ./build
        run: make -j4
      - name: Install Talipot core build
        working-directory: ./build
        run: make -j4 install
      - name: Run Talipot core build unit tests
        working-directory: ./build
        run: make tests
      - name: Configure Talipot complete build with CMake
        working-directory: ./build
        run: cmake .
          -DTALIPOT_BUILD_CORE_ONLY=OFF
          -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
      - name: Talipot complete build
        working-directory: ./build
        run: make -j4
      - name: Install Talipot complete build
        working-directory: ./build
        run: make -j4 install
      - name: Run Talipot complete build unit tests
        working-directory: ./build
        run: make tests
      - name: Generate Talipot dmg bundle
        working-directory: ./build
        run: make bundle
      - name: Get Talipot version
        id: get-talipot-version
        run: |
          echo "::set-output name=version::$(bash build/talipot-config --version)"
        shell: bash
      - name: Get macOS version
        id: get-macos-version
        run: |
          version=$(sw_vers -productVersion)
          major_version=$(echo $version | cut -d. -f1)
          minor_version=$(echo $version | cut -d. -f2)
          echo "::set-output name=version::$major_version.$minor_version"
        shell: bash
      - if: github.ref == 'refs/heads/master'
        name: Upload Taliot dmg bundle to Bintray
        uses: masofcon/upload-to-bintray-github-action@master
        with:
          source_path:
            ./build/Talipot-${{ steps.get-talipot-version.outputs.version }}
            -macOS-${{ steps.get-macos-version.outputs.version }}.dmg
          api_user: anlambert
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository: talipot_binaries
          package: Talipot
          version: ${{ steps.get-talipot-version.outputs.version }}
          publish: true
          override: 1
