name: macos-macports-wheels-build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  macos:
    name: Talipot wheel build for Python ${{ matrix.python-version }}
      on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        config:
          - os: macos-26-intel
            arch: x86_64
          - os: macos-15
            arch: arm64

    env:
      CLANG_VERSION: 20
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v5
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: python-install
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build and twine Python packages
        run: |
          which python
          python --version
          sudo pip install twine build
      - name: Install MacPorts
        run: |
          curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
          source ./macports-ci install --sync=rsync
      - name: Set macOS deployment target and install MacOSX sdk 11.3
        run: |
          echo 'macosx_deployment_target 11.0' | sudo tee -a /opt/local/etc/macports/macports.conf
          echo 'macosx_sdk_version 11.3' | sudo tee -a /opt/local/etc/macports/macports.conf
          curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          tar -xzf MacOSX11.3.sdk.tar.xz
          sudo mv MacOSX11.3.sdk /Library/Developer/CommandLineTools/SDKs/
      - name: Install Talipot build dependencies
        run: |
          # install libiconv, zlib and zstd from source first
          sudo port -N -s install libiconv
          # these dependencies are not required to be built from source
          sudo port -N install ncurses xz gettext lz4
          sudo port -N -s install zlib zstd
          # install binary packages and dependencies to avoid building them from source
          sudo port -N install ccache cmake bison python313 texinfo gawk graphviz
          # uninstall packages that need to be built from source to get correct deployment target
          sudo port -f uninstall openssl3 expat libtool libssh2 pcre2 libomp qhull yajl libgit2 graphviz
          # install libraries that need to be bundled in wheel from source
          sudo port -N -s install openssl3 expat libtool libssh2 pcre2 libomp qhull yajl libgit2 graphviz
      - name: Prepare ccache timestamp
        id: get-current-date
        run: |
          echo "date=$(date -u "+%Y-%m-%d-%H-%m-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Get ccache directory
        id: get-cccache-dir
        run: |
          ccache_dir=$(ccache -sv | grep "Cache directory" | awk '{print $3}')
          echo "ccache-dir=$ccache_dir" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.get-cccache-dir.outputs.ccache-dir }}
            /Users/runner/.macports-ci-ccache
          key: macos-wheels-ccache-${{ matrix.python-version }}-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            ${{ matrix.config.os }}-ccache-${{ matrix.python-version }}-
      - name: Sets CIBW_BUILD and SDKROOT environment variable
        env:
          pyVer: "${{matrix.python-version}}"
          arch: "${{matrix.config.arch}}"
        run: |
          echo "CIBW_BUILD=cp${pyVer/./}-macosx_$arch" >> $GITHUB_ENV
          echo "SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk" >> $GITHUB_ENV
      - name: Build Talipot wheel with cibuildwheel
        run: |
          pip install cibuildwheel --user
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
      - name: Test built wheel can be installed and imported
        working-directory: wheelhouse
        run: |
          pip install $(ls -t | head -1)
          python -c "from talipot import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
          python -c "from talipot import tlp; print(tlp.getImportPluginsList())"
      - uses: actions/upload-artifact@v4
        with:
          name: talipot-wheel-${{ matrix.python-version }}-${{ matrix.config.arch }}
          path: ./wheelhouse/*.whl
      - name: Publish Talipot wheel to TestPyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          twine check wheelhouse/*
          twine upload --skip-existing wheelhouse/*
