name: manylinux-wheel-build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  manylinux:
    name: Talipot manylinux ${{ matrix.python-version }} wheel build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v5
      - name: Get current date
        id: get-current-date
        run: |
          echo "date=$(date -u "+%Y-%m-%d-%H-%m-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: /ccache
          key: manylinux2014-ccache-${{ matrix.python-version }}-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            manylinux2014-ccache-${{ matrix.python-version }}-
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: python-install
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sets CIBW_BUILD environment variable
        env:
          pyVer: "${{matrix.python-version}}"
        run: |
          echo "CIBW_BUILD=cp${pyVer/./}-manylinux_x86_64" >> $GITHUB_ENV
      - name: Build Talipot wheel with cibuildwheel
        run: |
          sudo apt install python3-pip
          pip3 install cibuildwheel --user
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CCACHE_DIR: /host/ccache
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL: >
            mkdir /host/ccache &&
            yum -y install epel-release ccache &&
            yum -y install zlib-devel libzstd-devel yajl-devel qhull-devel graphviz-devel libgit2-devel
      - name: Test wheel can be installed and talipot module imported
        run: |
          $Python3_ROOT_DIR/bin/pip install $(ls -t | head -1)
          $Python3_ROOT_DIR/bin/python -c "
          from talipot import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
          $Python3_ROOT_DIR/bin/python -c "
          from talipot import tlp; print(tlp.getImportPluginsList())"
        working-directory: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: talipot-wheel-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
      - name: Publish Talipot wheel to TestPyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: wheelhouse/
          skip-existing: true
