name: manylinux-wheel-build
on: [push, pull_request]
jobs:
  manylinux:
    name: Talipot manylinux Python wheel build on CentOS 7.9
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Talipot code
        uses: actions/checkout@v3
      - name: Get current date
        id: get-current-date
        run: |
          echo "date=$(date -u "+%Y-%m-%d-%H-%m-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache files
        uses: actions/cache@v3
        with:
          path: ~/ccache
          key: manylinux2014-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            manylinux2014-ccache-
      - name: Pull ${{ env.DOCKER_IMAGE }} docker image
        run: sudo docker pull ${DOCKER_IMAGE}
      - name: Create ccache docker volume
        run: sudo docker create
          -v ~/ccache:/ccache
          --name ccache
          ${DOCKER_IMAGE}
      - name: Build and upload Talipot Python wheel
        run: sudo docker run
          -e CCACHE_DIR=/ccache
          --volumes-from ccache
          -v `pwd`:/talipot:rw
          ${DOCKER_IMAGE}
          /bin/bash -c
          "bash -x /talipot/bundlers/linux/talipot_python_wheels_manylinux_build.sh
          ${{ secrets.TEST_PYPI_API_TOKEN }}
          ${{ github.ref }}"
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Test uploaded wheel
        working-directory: tests/python
        run: |
          # wait one minute to ensure freshly uploaded wheels are registered on PyPI
          sleep 60

          pip3 install --upgrade pip --user
          pip3 install --index-url https://test.pypi.org/simple/ talipot --user
          python3 -c "from talipot import tlp; print(tlp.getLayoutAlgorithmPluginsList())"
          TALIPOT_BUILD_DIR= python3 -m unittest discover
